const express = require("express");
const router = express.Router();
const studentController = require("../controllers/studentController");
router.get("/", studentController.getAllStudents);
router.get("/add", studentController.showAddForm);
router.post("/add", studentController.addStudent);
router.get("/edit/:id", studentController.showEditForm);
router.post("/update/:id", studentController.updateStudent);
router.get("/delete/:id", studentController.deleteStudent);
router.get("/view/:id", studentController.viewStudent);
module.exports = router;